package com.horae.app.ui.common

import androidx.compose.runtime.Composable
import com.horae.app.data.AppSettings

/**
 * 应用内双语文案表：随 AppSettings.languageIndex 即时切换。
 * lang：0 = 中文，1 = English
 */
data class AppStrings(
    // ---------- 通用 ----------
    val back: String,
    val cancel: String,
    val save: String,
    val confirm: String,
    val nextStep: String,
    val done: String,
    val delete: String,
    val edit: String,
    val goEnable: String,
    val scheduleFallback: String,
    val allDay: String,
    val loading: String,
    // ---------- 看板 ----------
    val addSchedule: String,
    val scheduleList: String,
    val more: String,
    val backToToday: String,
    val search: String,
    val settings: String,
    val collapseHeader: String,
    val expandHeader: String,
    val timeLabel: String,
    val locationLabel: String,
    val noteLabel: String,
    // ---------- 列表页 ----------
    val emptyTitle: String,
    val emptyHint: String,
    val nextDay: String,
    // ---------- 搜索页 ----------
    val searchPlaceholder: String,
    val searchHint: String,
    val searchNoResult: String,
    // ---------- 编辑页 ----------
    val editSchedule: String,
    val titlePlaceholder: String,
    val locationPlaceholder: String,
    val start: String,
    val end: String,
    val repeat: String,
    val repeatEnd: String,
    val remind: String,
    val notePlaceholder: String,
    val color: String,
    val never: String,
    val untilDate: String,
    val untilCount: String,
    val timesFmt: (Int) -> String,
    val customRepeat: String,
    val freqLabel: String,
    val interval: String,
    val cyclePrefix: String,
    val countLabel: String,
    val repeatCountTitle: String,
    val monthTitle: (java.time.YearMonth) -> String,
    val titleRequired: String,
    val endAfterStart: String,
    val overlapBefore: String,
    val overlapMid: String,
    val overlapAfter: String,
    val deleteSchedule: String,
    val deleteTitle: String,
    val deleteMessage: String,
    val hour: String,
    val minute: String,
    // ---------- 看板条显示 ----------
    val boardDisplay: String,
    val showStartTimeLabel: String,
    val showEndTimeLabel: String,
    val overflowTitle: String,
    val overflowMsg: String,
    val showAnyway: String,
    val autoFit: String,
    // ---------- 提醒权限引导 ----------
    val permTitle: String,
    val permNotifTitle: String,
    val permNotifDesc: String,
    val permAutoTitle: String,
    val permAutoDesc: String,
    val permFooter: String,
    // ---------- 设置页 ----------
    val boardTheme: String,
    val axisRange: String,
    val sensitivity: String,
    val low: String,
    val high: String,
    val about: String,
    val author: String,
    val authorName: String,
    val openSource: String,
    val language: String,
    // ---------- 通知 ----------
    val notifChannelName: String,
    val notifChannelDesc: String,
    val notifStartFmt: (String) -> String,
    val notifFallbackTitle: String,
)

val StringsZh = AppStrings(
    back = "返回",
    cancel = "取消",
    save = "保存",
    confirm = "确定",
    nextStep = "下一步",
    done = "完成",
    delete = "删除",
    edit = "编辑",
    goEnable = "去开启",
    scheduleFallback = "日程",
    allDay = "全天",
    loading = "加载中…",
    addSchedule = "添加日程",
    scheduleList = "日程列表",
    more = "更多",
    backToToday = "回到今天",
    search = "搜索",
    settings = "设置",
    collapseHeader = "收起标题栏",
    expandHeader = "展开标题栏",
    timeLabel = "时间",
    locationLabel = "地点",
    noteLabel = "备注",
    emptyTitle = "这一天还没有日程",
    emptyHint = "点击下方「添加日程」开始安排",
    nextDay = "次日",
    searchPlaceholder = "搜索标题、地点、备注",
    searchHint = "输入关键词搜索日程",
    searchNoResult = "无匹配日程",
    editSchedule = "编辑日程",
    titlePlaceholder = "标题",
    locationPlaceholder = "位置",
    start = "开始",
    end = "结束",
    repeat = "重复",
    repeatEnd = "结束重复",
    remind = "提醒",
    notePlaceholder = "备注",
    color = "颜色",
    never = "永不",
    untilDate = "时间",
    untilCount = "次数",
    timesFmt = { "$it 次" },
    customRepeat = "自定义重复",
    freqLabel = "频率",
    interval = "间隔",
    cyclePrefix = "重复周期：",
    countLabel = "次数",
    repeatCountTitle = "重复次数",
    monthTitle = { "${it.year}年${it.monthValue}月" },
    titleRequired = "请填写标题",
    endAfterStart = "结束时间必须晚于开始时间",
    overlapBefore = "与「",
    overlapMid = "」时间段重合（",
    overlapAfter = "），请调整时间",
    deleteSchedule = "删除日程",
    deleteTitle = "删除日程？",
    deleteMessage = "该日程及其提醒将被移除。",
    hour = "小时",
    minute = "分钟",
    boardDisplay = "看板显示",
    showStartTimeLabel = "开始时间",
    showEndTimeLabel = "结束时间",
    overflowTitle = "日程条显示提醒",
    overflowMsg = "勾选的显示内容在部分日程条上可能放不下，超出部分会用 … 截断。仍按所选内容显示吗？",
    showAnyway = "仍然显示",
    autoFit = "自动适配",
    permTitle = "开启提醒所需权限",
    permNotifTitle = "通知权限",
    permNotifDesc = "允许 Horae 弹出提醒通知",
    permAutoTitle = "自启动",
    permAutoDesc = "允许 Horae 后台启动，否则到点无法提醒",
    permFooter = "两项都开启后，提醒即可准点显示在通知栏",
    boardTheme = "看板主题",
    axisRange = "纵轴显示范围",
    sensitivity = "滑动灵敏度",
    low = "低",
    high = "高",
    about = "关于",
    author = "作者",
    authorName = "wangce",
    openSource = "开源地址",
    language = "语言",
    notifChannelName = "日程提醒",
    notifChannelDesc = "日程开始前的提醒通知",
    notifStartFmt = { "$it 开始" },
    notifFallbackTitle = "日程提醒",
)

val StringsEn = AppStrings(
    back = "Back",
    cancel = "Cancel",
    save = "Save",
    confirm = "OK",
    nextStep = "Next",
    done = "Done",
    delete = "Delete",
    edit = "Edit",
    goEnable = "Enable",
    scheduleFallback = "Schedule",
    allDay = "All day",
    loading = "Loading…",
    addSchedule = "Add Schedule",
    scheduleList = "Schedule list",
    more = "More",
    backToToday = "Back to Today",
    search = "Search",
    settings = "Settings",
    collapseHeader = "Collapse header",
    expandHeader = "Expand header",
    timeLabel = "Time",
    locationLabel = "Location",
    noteLabel = "Note",
    emptyTitle = "Nothing scheduled this day",
    emptyHint = "Tap \"Add Schedule\" below to get started",
    nextDay = "Next day",
    searchPlaceholder = "Search title, location, note",
    searchHint = "Type keywords to search schedules",
    searchNoResult = "No matching schedules",
    editSchedule = "Edit Schedule",
    titlePlaceholder = "Title",
    locationPlaceholder = "Location",
    start = "Start",
    end = "End",
    repeat = "Repeat",
    repeatEnd = "End Repeat",
    remind = "Alert",
    notePlaceholder = "Note",
    color = "Color",
    never = "Never",
    untilDate = "On date",
    untilCount = "After",
    timesFmt = { "$it times" },
    customRepeat = "Custom Repeat",
    freqLabel = "Frequency",
    interval = "Interval",
    cyclePrefix = "Repeats: ",
    countLabel = "Times",
    repeatCountTitle = "Repeat Count",
    monthTitle = {
        it.month.getDisplayName(java.time.format.TextStyle.FULL, java.util.Locale.ENGLISH) + " " + it.year
    },
    titleRequired = "Title is required",
    endAfterStart = "End time must be after start time",
    overlapBefore = "Overlaps with \"",
    overlapMid = "\" (",
    overlapAfter = "), please adjust the time",
    deleteSchedule = "Delete Schedule",
    deleteTitle = "Delete schedule?",
    deleteMessage = "The schedule and its alert will be removed.",
    hour = "Hour",
    minute = "Minute",
    boardDisplay = "Board Display",
    showStartTimeLabel = "Start time",
    showEndTimeLabel = "End time",
    overflowTitle = "Schedule block display",
    overflowMsg = "The selected details may not fully fit in some schedule blocks and will be truncated with …. Show them as selected anyway?",
    showAnyway = "Show Anyway",
    autoFit = "Auto Fit",
    permTitle = "Permissions needed for alerts",
    permNotifTitle = "Notification permission",
    permNotifDesc = "Allow Horae to post alert notifications",
    permAutoTitle = "Auto-start",
    permAutoDesc = "Allow Horae to run in background, or alerts won't fire on time",
    permFooter = "Enable both so alerts arrive on time in the notification bar",
    boardTheme = "Board Theme",
    axisRange = "Time Axis Range",
    sensitivity = "Scroll Sensitivity",
    low = "Low",
    high = "High",
    about = "About",
    author = "Author",
    authorName = "wangce",
    openSource = "Open Source",
    language = "Language",
    notifChannelName = "Schedule Alerts",
    notifChannelDesc = "Notifications before a schedule starts",
    notifStartFmt = { "Starts $it" },
    notifFallbackTitle = "Schedule Alert",
)

/** 按语言序号取文案表（非组合环境也可用） */
fun appStrings(lang: Int): AppStrings = if (lang == 1) StringsEn else StringsZh

/** 组合环境：读取语言设置，切换时自动重组 */
@Composable
fun strings(): AppStrings = appStrings(AppSettings.languageIndex)
